### PR TITLE
DateTime binding

### PR DESCRIPTION
**Pull request by hungthai1401**
@tpetry This PR includes the format of DateTime.
When we have DateTime bindings, we will occur the error: `Error: Object of class DateTime could not be converted to string`.
I have fixed with some unit test cases.

### CODE REVIEW

**Comment by tpetry** [comment]
Thanks for the PR. I'll check it later. My original idea was to not do any conversions by myself and only rely on the Laravel ones to execute absolute identical. I have to research why that failed...

**Comment by hungthai1401** [comment]
@tpetry thanks for your great package. You can see at https://github.com/laravel/framework/blob/6d690edda8c5b0d400a8753def02d9ecd3e98e40/src/Illuminate/Database/Connection.php#L721

**Comment by tpetry** [comment]
Thanks for finding the issue. The fix is now released with version `1.0.2`

**Comment by hungthai1401** [comment]
thanks. it's nice

**Pull request merged**
